version: '3.9'
services:
  app:
    restart: always
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      

  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    env_file:
      - .env
  
  redis:
    restart: always
    image: redis:7.0-alpine


  telegrambot:
    restart: always
    build: .
    command: bash -c "python3 -m telegrambot.bot"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  worker:
    restart: always
    build: .
    command: celery -A sauna_landing worker -l INFO
    env_file:
      - .env
    depends_on:
      - app

  migrations:
    build: .
    command: bash -c "python3 manage.py migrate"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: "no"
    profiles:
      - migrate

volumes:
  postgres-data:

  