version: '3.9'
services:
  app:
    restart: unless-stopped
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
      - migrate

  postgres:
    restart: unless-stopped
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
      - minio
    env_file:
      - .env

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file:
      - .env
    volumes:
      - minio-data:/data
    ports:
      - "9001:9001"

  migrate:
    build: .
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput || true"
    env_file:
      - .env
    depends_on:
      - postgres


volumes:
  postgres-data:
  minio-data: