proxy_cache_path /var/cache/nginx
                 levels=1:2
                 keys_zone=django_cache:100m
                 max_size=1g
                 inactive=60m
                 use_temp_path=off;

server {
    listen 80;
    server_name nginx.your-domain.com;

    client_max_body_size 50M;

    location /static/ {
        alias /app/static/;

        expires 1y;
        add_header Cache-Control "public, immutable";

        access_log off;
    }

    location /media/ {

        proxy_pass http://minio:9000/media/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        expires off;
        add_header Cache-Control "private, must-revalidate";

        proxy_pass_header ETag;
        proxy_pass_header Last-Modified;

        proxy_buffering off;

        proxy_cache off;
    }

    location /admin/ {

        proxy_pass http://app:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_no_cache 1;
        proxy_cache_bypass 1;
    }

    location / {

        proxy_pass http://app:8000/;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_redirect off;

        proxy_cache django_cache;

        proxy_cache_methods GET HEAD;

        proxy_cache_key "$scheme$request_method$host$request_uri";

        proxy_cache_valid 200 5m;

        proxy_cache_use_stale error
                                timeout
                                updating
                                http_500
                                http_502
                                http_503
                                http_504;

        add_header X-Cache-Status $upstream_cache_status;
    }
}