# Generated by Django 5.1 on 2024-08-25 15:12

import landing.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PictureAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    landing.utils.models.SizeRestrictedImageField(
                        blank=True, null=True, upload_to=""
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PictureDecoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    landing.utils.models.SizeRestrictedImageField(
                        blank=True, null=True, upload_to=""
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
