# Generated by Django 4.2.16 on 2026-05-30 12:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "departments",
                    wagtail.fields.StreamField(
                        [("department", 14)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Название отделения",
                                    "max_length": 60,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "required": False,
                                    "verbose_name": "Описание отделения",
                                },
                            ),
                            2: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Отключить отделение",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("image", 3)]],
                                {"required": False, "verbose_name": "Фотографии"},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "День недели",
                                    "max_length": 20,
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Описание / часы",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("day", 5), ("info", 6)]],
                                {"icon": "time", "label": "День режима работы"},
                            ),
                            8: (
                                "wagtail.blocks.ListBlock",
                                (7,),
                                {"label": "Режим работы", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Услуга", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.DecimalBlock",
                                (),
                                {
                                    "decimal_places": 0,
                                    "label": "Цена",
                                    "max_digits": 6,
                                    "max_value": 100000,
                                    "min_value": 100,
                                    "required": True,
                                },
                            ),
                            11: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Описание", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 9), ("price", 10), ("description", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.ListBlock",
                                (12,),
                                {"label": "Прайскурант", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("disabled", 2),
                                        ("images", 4),
                                        ("working_hours", 8),
                                        ("pricelist", 13),
                                    ]
                                ],
                                {"required": False},
                            ),
                        },
                        verbose_name="Отделения сауны",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, verbose_name="Номер телефона"),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                (
                    "answer",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Ответ"),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_content",
                    wagtail.fields.StreamField(
                        [("custom_block", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"label": "HTML код", "required": False},
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("html", 0)]], {}),
                        },
                        verbose_name="Кастомный HTML/CSS контент",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Картинка для карусели",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_images",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
