# Generated by Django 4.2.16 on 2024-12-14 13:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="custom_content",
            field=wagtail.fields.StreamField(
                [("custom_block", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "HTML код", "required": False},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("html", 0)]], {}),
                },
                verbose_name="Кастомный HTML/CSS контент",
            ),
        ),
    ]
