# Generated by Django 4.2.16 on 2024-11-22 19:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselimage",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="caption_position_x",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="caption_position_y",
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="custom_content",
            field=wagtail.fields.StreamField(
                [("custom_block", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "HTML код", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CSS классы", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Inline стили (CSS)", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("html", 0), ("css_class", 1), ("style", 2)]],
                        {},
                    ),
                },
                verbose_name="Кастомный HTML/CSS контент",
            ),
        ),
    ]
