# Generated by Django 4.2.16 on 2024-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_description_alter_faq_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="caption_position_x",
            field=models.CharField(
                blank=True,
                default="50%",
                max_length=10,
                verbose_name="Горизонтальная позиция текста (в %)",
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="caption_position_y",
            field=models.CharField(
                blank=True,
                default="90%",
                max_length=10,
                verbose_name="Вертикальная позиция текста (в %)",
            ),
        ),
    ]
