# Generated by Django 4.2.16 on 2024-11-23 13:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_carouselimage_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="custom_content",
            field=wagtail.fields.StreamField(
                [("custom_block", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "HTML с шаблонными тегами", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CSS классы", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Inline стили (CSS)", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("html_template", 0), ("css_class", 1), ("style", 2)]],
                        {"label": "HTML с шаблонными тегами", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("html", 3), ("css_class", 1), ("style", 2)]],
                        {},
                    ),
                },
                verbose_name="Кастомный HTML/CSS контент",
            ),
        ),
    ]
