# Generated by Django 4.2.16 on 2026-04-27 22:45

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_promotion_image_alter_homepage_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="departments",
            field=wagtail.fields.StreamField(
                [("department", 7)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Название отделения",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": False, "verbose_name": "Описание отделения"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 2)]],
                        {"required": False, "verbose_name": "Фотографии"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Услуга", "required": True},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("service", 4)]], {}),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {"label": "Прайскурант", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("images", 3),
                                ("pricelist", 6),
                            ]
                        ],
                        {"required": False},
                    ),
                },
                verbose_name="Отделения сауны",
            ),
        ),
    ]
