# Generated by Django 4.2.16 on 2024-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("home", "0003_carouselimage_caption_position_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="overlay_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Дополнительные изображения",
            ),
        ),
    ]
