# Generated by Django 4.2.16 on 2024-11-02 19:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="departments",
            field=wagtail.fields.StreamField(
                [("sauna_department", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Название отделения",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Описание отделения", "required": True},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {},
                    ),
                },
                verbose_name="Отделения сауны",
            ),
        ),
    ]
