# Generated by Django 4.2.16 on 2024-11-02 20:19

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="departments",
            field=wagtail.fields.StreamField(
                [("department", 3)],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": False, "verbose_name": "Описание отделения"},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 1)]],
                        {"verbose_name": "Фотографии"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("description", 0), ("images", 2)]],
                        {},
                    ),
                },
                verbose_name="Отделения сауны",
            ),
        ),
    ]
