# Generated by Django 4.2.16 on 2024-11-06 18:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("home", "0007_alter_homepage_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="departments",
            field=wagtail.fields.StreamField(
                [("department", 4)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Название отделения",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": False, "verbose_name": "Описание отделения"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 2)]],
                        {"required": False, "verbose_name": "Фотографии"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("images", 3)]],
                        {"required": False},
                    ),
                },
                verbose_name="Отделения сауны",
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
