# Generated by Django 4.2.16 on 2026-04-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_homepage_departments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
